### ISSUE TITLE
runtime_error: Could not initialize OpenGL functions.

### ISSUE THREAD

**Issue by wghou** [RThomas96/Medical-Image-3D-Visualisation-Software#2]
Hi, everyone!

I clone the source code and install external libraries according to the BUILD2.md, I build the project secussfully. But when i run the sofrware, i got this error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not initialize OpenGL functions.
Aborted (core dumped)
```

I check the code and also my system setup, i found that this error arised from mismatch of the version of OpenGL. In the source code, the opengl 3.2 is used, but in my computer system, the opengl 3.1 is installed. So the error raised.

There may be two solutions of this error: update OpenGL to v3.2, or change the source code.

my system is Ubuntu 20.04 and i install OpenGL using the following cmd:
```
sudo apt-update
sudo apt-get install mesa-utils
```

Wenguo Hou

**Comment by wghou** [comment]
Update:
I'm not very familar with the Linux system, so i made confusion of the OpenGL version.

When i install opengl by `apt-get install libgl1-mesa-dev`, the default version of OpenGL seems be v3.1. But the Medical-Image-3D-Visualisation-Software **need OpenGL-v3.2**, so we need to configure the version of OpenGL. I following this article [[Updating OpenGL from version 3.0 to latest 4.5](https://askubuntu.com/questions/928538/updating-opengl-from-version-3-0-to-latest-4-5)](https://askubuntu.com/questions/928538/updating-opengl-from-version-3-0-to-latest-4-5), as
```
glxinfo|grep OpenGL
export MESA_GL_VERSION_OVERRIDE=3.2
glxinfo | grep "OpenGL version"
echo 'export MESA_GL_VERSION_OVERRIDE=3.2' >> ~/.bashrc
```

Maybe some description can be added in `BUILD.md`, Just for people who are not familiar with Linux. Thanks! @RThomas96 

Wenguo Hou

**Comment by wghou** [comment]
Please use Ubuntu 22.04.4 LTS as the authors recommanded. Otherwise,  a lot of modifications would be needed.

**Comment by RThomas96** [comment]
Thank you very much for your feedback. I updated the building instructions.

If you have other tips that I could add, please don't hesitate :)
